version: '3.8'
services: 
  postgres:
    image: postgres:13
    container_name: postgresprisma
    restart: always
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: nestAuth
      POSTGRES_PASSWORD: nestAuth
      POSTGRES_DB: nestAuth
volumes: 
  postgres:
    name: nest-prisma-docker-db