
POST http://localhost:3080/api/v1/users HTTP/1.1
Content-Type: application/json

{
  "name": "Renato Daltiba Schneider",
  "email": "renatodaltibas@gmail.com",
  "phone": "69992561022",
  "password": "27.9.1995Re",
  "offers": false
}

###

POST http://localhost:3080/api/auth/login HTTP/1.1
Content-Type: application/json

{
  "phoneoremail": "699925610dasdas224",
  "password": "27.9.1995Re"
}


###
GET http://localhost:3080/api/v1/users/me HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJlOWU0NGE5NS1hMzIwLTRlNzUtYmNhNS0yYmZmMmQwZjRlYjkiLCJlbWFpbCI6InJlbmF0b2RhbHRpYmFAZ21haWwuY29tIiwiaWF0IjoxNjUzMzE4Njg3LCJleHAiOjE2NTMzNjE4ODd9.OJOi1MYPzyCcjYZVja01YA5qI6a-7Q5Y-5n6xRC8Ioc
